### PR TITLE
Viewloader2.0

### PR DESCRIPTION
**Pull request by chrisbuttery**
This PR adds
- general house cleaning to the main component
- npm scripts
- examples
- tests
- comments
- documentation

### CODE REVIEW

**Comment by makenosound** [comment]
@chrisbuttery Looks great. Only thing I think that needs coverage in the tests is ensuring the different types of `props` are handled correctly: `Strings` vs `JSON` blobs. Otherwise :+1::exclamation:

**Comment by chrisbuttery** [comment]
@makenosound Doooone!

Lastly, we'll need to :
- merge and possibly update the link to the examples.
- git tag `2.0.0`
- log in to npm and snaggle [viewloader](https://www.npmjs.com/search?q=viewloader) + publish.

**Comment by chrisbuttery** [comment]
@makenosound actually, it just needs a minor version bump as there's no breaking changes - just a refactor

**Comment by chrisbuttery** [comment]
@makenosound `1.1.0` instead of `2.0.0`

**Comment by makenosound** [comment]
Woop. Sounds good to me.

**Pull request merged**
